/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CurrencyConvereter2;

import javax.swing.JOptionPane;

/**
 *
 * @author youro
 */
public class CurrencyConvereter2 extends javax.swing.JFrame {

    String[] currencyUnits = {
        "Currency", "Dollar", "Taka", "Real", "Rupee", "Rial", "Riyal", "Shilling", "Dirham", "Dollar", "dong"};
    double Australian_Dollar = 0.014;
    double Bangladeshi_Taka = 1;
    double Brazilian_Real = 0.051;
    double Pakistani_Rupee = 2.17;
    double Qatari_Rial = 0.035;
    double Saudi_Riyal = 0.036;
    double Somali_Shilling = 5.52;
    double United_Arab_Emirates_Dirham = 0.036;
    double United_States_Dollar = 0.0097;
    double Vietnamese_dong = 232.49;

    public CurrencyConvereter2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        secondChooseCountry = new javax.swing.JComboBox<>();
        fastChooseCountry = new javax.swing.JComboBox<>();
        text2 = new javax.swing.JTextField();
        text1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fastCurrency = new javax.swing.JLabel();
        secondCurrency = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Currency Convereter");

        secondChooseCountry.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        secondChooseCountry.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose your country", "Australian Dollar", "Bangladeshi Taka", "Brazilian Real", "Pakistani Rupee", "Qatari Rial", "Saudi Riyal", "Somali Shilling", "United States Dollar", "United Arab Emirates Dirham", "Vietnamese dong" }));
        secondChooseCountry.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                secondChooseCountryItemStateChanged(evt);
            }
        });
        secondChooseCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondChooseCountryActionPerformed(evt);
            }
        });

        fastChooseCountry.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        fastChooseCountry.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose your country", "Australian Dollar", "Bangladeshi Taka", "Brazilian Real", "Pakistani Rupee", "Qatari Rial", "Saudi Riyal", "Somali Shilling", "United States Dollar", "United Arab Emirates Dirham", "Vietnamese dong" }));
        fastChooseCountry.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                fastChooseCountryItemStateChanged(evt);
            }
        });

        text2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        text1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        text1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("From Currency");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("To Currency");

        fastCurrency.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fastCurrency.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        fastCurrency.setText("Currency");

        secondCurrency.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        secondCurrency.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        secondCurrency.setText("Currency");

        jButton1.setBackground(new java.awt.Color(0, 0, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Convert Currency");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setText("Reset The System");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton3.setText("Exit Now");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(text1)
                                .addComponent(fastChooseCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(secondChooseCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(text2, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 149, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(secondCurrency)
                                    .addComponent(fastCurrency))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(176, 176, 176)
                .addComponent(jButton3)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(188, 188, 188))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fastChooseCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(text1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(fastCurrency))
                        .addGap(70, 70, 70)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(17, 17, 17)
                                .addComponent(secondChooseCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(text2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(secondCurrency, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap(83, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void secondChooseCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondChooseCountryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_secondChooseCountryActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Convert Currency
        if(fastChooseCountry.getSelectedIndex()==0 || secondChooseCountry.getSelectedIndex()==0 || text1.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Sorry you dont select both Country or maybe dont input your amount.","Error Message. Thank you for using our app",JOptionPane.INFORMATION_MESSAGE);
            return;
        }
            
        double amountToChange = Double.parseDouble(text1.getText());
        double amountInTk = 0.0,amountChanged;
        switch (fastChooseCountry.getSelectedItem().toString()) {
            case "Australian Dollar":
                amountInTk = amountToChange / Australian_Dollar;
                break;
            case "Bangladeshi Taka":
                amountInTk = amountToChange / Bangladeshi_Taka;
                break;
            case "Brazilian Real":
                amountInTk = amountToChange / Brazilian_Real;
                break;
            case "Pakistani Rupee":
                amountInTk = amountToChange / Pakistani_Rupee;
                break;
            case "Qatari Rial":
                amountInTk = amountToChange / Qatari_Rial;
                break;
            case "Saudi Riyal":
                amountInTk = amountToChange / Saudi_Riyal;
                break;
            case "Somali Shilling":
                amountInTk = amountToChange / Somali_Shilling;
                break;
            case "United Arab Emirates Dirham":
                amountInTk = amountToChange / United_Arab_Emirates_Dirham;
                break;
            case "United States Dollar":
                amountInTk = amountToChange / United_States_Dollar;
                break;
            case "Vietnamese dongr":
                amountInTk = amountToChange / Vietnamese_dong;
                break;
            default:
                amountInTk = 0.0;
        }
        switch (secondChooseCountry.getSelectedItem().toString()) {
            case "Australian Dollar":
                amountChanged = amountInTk * Australian_Dollar;
                break;
            case "Bangladeshi Taka":
                amountChanged = amountInTk * Bangladeshi_Taka;
                break;
            case "Brazilian Real":
                amountChanged = amountInTk * Brazilian_Real;
                break;
            case "Pakistani Rupee":
                amountChanged = amountInTk * Pakistani_Rupee;
                break;
            case "Qatari Rial":
                amountChanged = amountInTk * Qatari_Rial;
                break;
            case "Saudi Riyal":
                amountChanged = amountInTk * Saudi_Riyal;
                break;
            case "Somali Shilling":
                amountChanged = amountInTk * Somali_Shilling;
                break;
            case "United Arab Emirates Dirham":
                amountChanged = amountInTk * United_Arab_Emirates_Dirham;
                break;
            case "United States Dollar":
                amountChanged = amountInTk * United_States_Dollar;
                break;
            case "Vietnamese dong":
                amountChanged = amountInTk * Vietnamese_dong;
                break;
            default:
                amountChanged = amountInTk * 0.0;

        }
        String value = String.format("%.2f",amountChanged);
        text2.setText(value);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        fastChooseCountry.setSelectedIndex(0);
        secondChooseCountry.setSelectedIndex(0);
        text1.setText(null);
        text2.setText(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void text1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text1ActionPerformed

    private void fastChooseCountryItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_fastChooseCountryItemStateChanged

        int n = fastChooseCountry.getSelectedIndex();

        fastCurrency.setText(currencyUnits[n]);
    }//GEN-LAST:event_fastChooseCountryItemStateChanged

    private void secondChooseCountryItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_secondChooseCountryItemStateChanged
        int o = secondChooseCountry.getSelectedIndex();

        secondCurrency.setText(currencyUnits[o]);
    }//GEN-LAST:event_secondChooseCountryItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CurrencyConvereter2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CurrencyConvereter2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CurrencyConvereter2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CurrencyConvereter2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CurrencyConvereter2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> fastChooseCountry;
    private javax.swing.JLabel fastCurrency;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> secondChooseCountry;
    private javax.swing.JLabel secondCurrency;
    private javax.swing.JTextField text1;
    private javax.swing.JTextField text2;
    // End of variables declaration//GEN-END:variables
}
